tags = [
    "cool", "groovy", "awesome", "chill", "energetic",
    "upbeat", "relaxing", "dance", "melancholic", "experimental",
    "pop", "rock", "electronic", "hip-hop", "jazz",
    "indie", "alternative", "ambient", "funk", "soul",
    "reggae", "classical", "country", "rap", "blues",
    "folk", "punk", "metal", "r&b", "edm",
    "techno", "house", "trance", "trap", "dubstep",
    "ska", "latin", "reggaeton", "samba", "bossa nova",
    "world", "new age", "acoustic", "lo-fi", "synthwave",
    "grunge", "hardcore", "psychedelic", "downtempo", "chillwave",
    "dream pop", "post-rock", "electropop", "lo-fi hip-hop", "ambient pop",
    "trip hop", "disco", "funk rock", "shoegaze", "folk rock",
    "glam rock", "progressive rock", "space rock", "noise rock", "post-punk",
    "punk rock", "folk punk", "pop punk", "emo", "skate punk",
    "indie rock", "indie pop", "indie folk", "psychedelic rock", "blues rock",
    "hard rock", "heavy metal", "death metal", "black metal", "doom metal",
    "symphonic metal", "power metal", "progressive metal", "folk metal", "industrial metal",
    "alt-country", "country pop", "country rock", "bluegrass", "honky-tonk",
    "western swing", "southern rock", "rap rock", "trap metal", "rap metal",
    "gangsta rap", "conscious rap", "trap rap", "boom bap", "east coast hip-hop",
    "west coast hip-hop", "dirty south", "grime", "triplet flow", "trap soul",
    "neo-soul", "contemporary r&b", "new jack swing", "funk carioca", "baile funk",
    "merengue", "salsa", "cumbia", "bachata", "tango",
    "flamenco", "bollywood", "k-pop", "j-pop", "afrobeat",
    "highlife", "juju", "mbalax", "soukous", "kizomba",
    "folktronica", "psybient", "chiptune", "vaporwave", "funktronica",
    "idm", "triphop", "synthpop", "industrial", "darkwave",
    "minimal", "progressive", "big room", "trance", "happy hardcore",
    "future bass", "drum and bass", "liquid funk", "hardstyle", "gabber",
    "dub", "reggaedub", "dub techno", "ambient dub", "deep house",
    "acid house", "tech house", "microhouse", "progressive house", "latin house",
    "trapstep", "moombahton", "tropical house", "psytrance", "suomisaundi",
    "vocal trance", "goa trance", "dark psytrance", "ambient trance", "emotional trance",
    "glitch", "indietronica", "outsider house", "wonky", "jungle",
    "neurofunk", "liquid funk", "breakcore", "breakbeat", "hip-house",
    "electroswing", "dancehall", "bubbling", "tropical bass", "carnival",
    "mambo", "songo", "son montuno", "rumba", "bachata",
    "candombe", "forró", "frevo", "samba-reggae", "pagode",
    "bongo flava", "genge", "kapuka", "taarab", "bongo flava",
    "kuduro", "semba", "azonto", "highlife", "mbaqanga",
    "juju", "afrobeat", "afro house", "chimurenga", "afro jazz",
    "makossa", "bikutsi", "mbalax", "fuji", "apala",
    "kwaito", "kwela", "maskandi", "reggae", "dancehall",
    "ukulele", "bagpipes", "banjo", "cello", "didgeridoo",
    "flute", "harp", "saxophone", "violin", "accordion",
    "theremin", "kalimba", "xylophone", "marimba", "hang drum",
    "didgeridoo", "tabla", "djembe", "cajon", "steel drums",
    "sitar", "gamelan", "koto", "oud", "zheng",
    "shakuhachi", "erhu", "oud", "guzheng", "mbira",
    "oud", "kantele", "saung", "zither", "sarod",
    "nyckelharpa", "baglama", "bouzouki", "santoor", "saz",
    "trombone", "clarinet", "bassoon", "oboe", "piccolo",
    "melodica", "pan flute", "shofar", "alphorn", "vuvuzela",
    "didgeridoo", "klaxon", "siren", "whistle", "buzz",
    "white noise", "static", "rain", "thunderstorm", "fire crackling",
    "waves", "wind", "birds", "crickets", "cicadas",
    "city", "traffic", "crowd", "applause", "laughter",
    "footsteps", "heartbeat", "breathing", "clock", "bell",
    "whisper", "scream", "moan", "sigh", "cough",
    "sneeze", "snore", "hiccup", "yawn", "gulp",
    "slurp", "munch", "chew", "swallow", "gargle",
    "sputter", "hum", "grunt", "squeak", "sniff"
    # Add more tags as needed
]
